### ISSUE TITLE
Failed to resolve dependency on Android

### ISSUE THREAD

**Issue by AndriusWild** [Colossal1/plugin.video.SportsDevil#13]
Hello,
I am trying to install SportsDevil 2017.10.01 but the installation fails every time saying it failed to resolve a dependency. I don't know how to check kodi logs on Android so I can't tell what exactly is going on. Any help would be greatly appreciated.

**Comment by Gujal00** [comment]
You need the collossus common repository installed, then it will pull all the dependant modules as part of the install.

**Comment by devilsport** [comment]
can be closed
